service: salesforce-finance-contact-sync

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:sendMessage
    Resource: arn:aws:sqs:*:*:queue

plugins:
  - serverless-cloud-elements-plugin

functions:
  sync:
    handler: contactSync_babelized.eventHandler
    timeout: 30
    memorySize: 256
    events:
      - instance:
          resource: source
      - sqs:
          arn:
            Fn::GetAtt:
              - queue
              - Arn

resources:
  Resources:
    source:
      Type: CE::Element::sfdc
      Properties:
        id: ${env:SOURCE_ID}
    dest:
      Type: CE::Hub::general
      Properties:
        id: ${env:DEST_ID}
    account:
      Type: CE::Account
      Properties:
        userToken: ${env:USER_TOKEN}
        orgToken: ${env:ORG_TOKEN}
        baseUrl: ${env:BASE_URL}
    queue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "queue"

